### ISSUE TITLE
Ticket V1/MVP TODOs

### ISSUE THREAD

**Issue by erikdstock** [erikdstock/gatsby-theme-auth0-ts#2]
TODO:
- [x] README
- [x] add tests + CI (#6)
- [x] confirm types setup (#7)
- [x] Correct setup options with clear defaults for optional parameters (#8)
- [x] handle redirects using [authorize `state` option](https://auth0.com/docs/libraries/auth0js/v9#webauth-authorize-) (#9)
- [x] security audit (see `state` option above) (#10)

**Comment by erikdstock** [comment]
Closed by creating linked issues above.
